# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  graphqlproject:
    image: graphqlproject
    build:
      context: .
      dockerfile: GraphQLProject/GraphQLProject/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 5006:5006
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
